module.exports=[
    {
        name:"Amit",
        email:"amit@gmail.com",
        password:"12345",
    },
    {
        name:"Aditya",
        email:"aditya@gmail.com",
        password:"aditya",
    },
    {
        name:"Pankaj",
        email:"pankaj@gmail.com",
        password:"pankaj123",
    },
    {
        name:"Omkar",
        email:"omkar@gmail.com",
        password:"omkar123",
    },
    {
        name:"Anurag",
        email:"anurag@gmail.com",
        password:"anurag123",
    }
]